# Generated by Django 4.2.29 on 2026-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
    ]
