Algoritmo sin_titulo
	
	//NOTA: EN EL CICLO REPETITIVO MIENTRAS LA CONDICION
	//DE FIN DE CICLO SE EVALUA ANTES DE EJECUTAR CUALQUIER ACCION
	
	
	//DECLARACION DE VARIABLES 
	
	DEFINIR I COMO ENTERO
	DEFINIR N COMO ENTERO
	
	//INICIALIZACION DE VARIABLES
	
	N<-5 
	I<-0
	
	MIENTRAS I<N HACER 
		ESCRIBIR I 
		I <- I+1
	FinMientras
	ESCRIBIR 'FIN DEL CICLO MIENTRAS'
	
FinAlgoritmo
